Update documentation.yaml

diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -15,10 +15,10 @@ jobs:
         run: |
           sphinx-build -W --keep-going doc _build
           if [ $? -ne 0 ]; then
-            echo -e "\033[1;31mSphinx build FAILED\033[0m\n";
-            exit 1;
+            echo -e "\033[1;31mSphinx build FAILED\033[0m\n"
+            exit 1
           else
-            echo -e "\033[1;32mSphinx build PASSED\033[0m\n";
+            echo -e "\033[1;32mSphinx build PASSED\033[0m\n"
           fi
       - name: Set branch name
         id: branch
