Added result check to sphinx-build

diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -13,7 +13,13 @@ jobs:
           pip install sphinx==6.1.3 sphinx_rtd_theme sphinx-favicon myst_parser sphinx_sitemap
       - name: Sphinx build
         run: |
-          sphinx-build doc _build
+          sphinx-build -W --keep-going doc _build
+          if [ $? -ne 0 ]; then
+            echo -e "\033[1;31mSphinx build FAILED\033[0m\n";
+            exit 1;
+          else
+            echo -e "\033[1;32mSphinx build PASSED\033[0m\n";
+          fi
       - name: Set branch name
         id: branch
         run: echo "SUBDIR_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
